"""Add WhatsApp Campaign models

Revision ID: 0e08654b0f18
Revises: 0001
Create Date: 2026-09-22 13:30:24.687929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e08654b0f18'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_accounts',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('phone_number_id', sa.String(length=100), nullable=True),
    sa.Column('waba_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_whatsapp_accounts_account_id'), 'whatsapp_accounts', ['account_id'], unique=False)
    op.create_table('whatsapp_templates',
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('header_type', sa.String(length=50), nullable=True),
    sa.Column('header_content', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('footer', sa.String(length=500), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_whatsapp_templates_template_id'), 'whatsapp_templates', ['template_id'], unique=False)
    op.create_table('whatsapp_campaigns',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.String(length=32), nullable=True),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('data_source_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_contacts', sa.Integer(), nullable=False),
    sa.Column('successful_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.template_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_index(op.f('ix_whatsapp_campaigns_campaign_id'), 'whatsapp_campaigns', ['campaign_id'], unique=False)
    op.create_table('whatsapp_campaign_recipients',
    sa.Column('recipient_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['whatsapp_campaigns.campaign_id'], ),
    sa.PrimaryKeyConstraint('recipient_id')
    )
    op.create_index(op.f('ix_whatsapp_campaign_recipients_business_id'), 'whatsapp_campaign_recipients', ['business_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaign_recipients_campaign_id'), 'whatsapp_campaign_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaign_recipients_phone'), 'whatsapp_campaign_recipients', ['phone'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaign_recipients_recipient_id'), 'whatsapp_campaign_recipients', ['recipient_id'], unique=False)
    op.create_table('whatsapp_campaign_logs',
    sa.Column('log_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('recipient_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider_status', sa.String(length=100), nullable=True),
    sa.Column('provider_code', sa.String(length=50), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['whatsapp_campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['whatsapp_campaign_recipients.recipient_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_whatsapp_campaign_logs_campaign_id'), 'whatsapp_campaign_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_campaign_logs_log_id'), 'whatsapp_campaign_logs', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_campaign_logs_log_id'), table_name='whatsapp_campaign_logs')
    op.drop_index(op.f('ix_whatsapp_campaign_logs_campaign_id'), table_name='whatsapp_campaign_logs')
    op.drop_table('whatsapp_campaign_logs')
    op.drop_index(op.f('ix_whatsapp_campaign_recipients_recipient_id'), table_name='whatsapp_campaign_recipients')
    op.drop_index(op.f('ix_whatsapp_campaign_recipients_phone'), table_name='whatsapp_campaign_recipients')
    op.drop_index(op.f('ix_whatsapp_campaign_recipients_campaign_id'), table_name='whatsapp_campaign_recipients')
    op.drop_index(op.f('ix_whatsapp_campaign_recipients_business_id'), table_name='whatsapp_campaign_recipients')
    op.drop_table('whatsapp_campaign_recipients')
    op.drop_index(op.f('ix_whatsapp_campaigns_campaign_id'), table_name='whatsapp_campaigns')
    op.drop_table('whatsapp_campaigns')
    op.drop_index(op.f('ix_whatsapp_templates_template_id'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_accounts_account_id'), table_name='whatsapp_accounts')
    op.drop_table('whatsapp_accounts')
    # ### end Alembic commands ###
